---
name: Keypad Mgmt
version: dev
slug: keypad-app
description: Keypad App add-on by CJ Ramseyer
url: https://github.com/cjramseyer/keypad-app
codenotary: cj@ramseyer.org
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)