---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      addon_dir: keypad-app
